// Generated by CoffeeScript 1.6.2
(function() {
  var $, Card, CardDeck, HtmlContent, Main, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Card = (function() {
    function Card() {}

    return Card;

  })();

  CardDeck = (function() {
    function CardDeck() {}

    return CardDeck;

  })();

  HtmlContent = (function() {
    var content, contentArray, contentArrayLength, drag, dragOnceOver, filter, parseCallback, queue, refine, self;

    self = HtmlContent;

    content = '';

    contentArray = [];

    contentArrayLength = 0;

    queue = [];

    parseCallback = null;

    /*
    	# 内容抓取
    	#
    	# 按 #*4分割(从开始到#*4)
    	# 找到第一个##行
    	# 判断是否为[*]
    	# 同理====以及剩余部分(到$$$$前）
    	# 分析下一个part的开头是否为[*]
    */


    drag = function(startLine) {
      var handles, index, recursion, result, rule, text;

      result = [];
      text = contentArray[startLine];
      rule = [null, '####', '====', null];
      index = 0;
      handles = [];
      recursion = function() {
        if (index < rule.length - 1) {
          return filter(text, rule[index], rule[index + 1], false, function(_res) {
            result.push(_res);
            index++;
            return recursion();
          });
        } else {
          return filter(contentArray[startLine + 1], null, null, true, function(_res) {
            result.push(_res);
            return dragOnceOver(startLine, result);
          });
        }
      };
      return recursion();
    };

    filter = function(text, startDelimiter, endDelimiter, fromFront, callback) {
      var data, end, line, matchLine, result, start, _i, _j, _len, _len1, _r;

      matchLine = function(line, fromFront) {
        var m, reg;

        reg = fromFront ? /^\[(.*)\]/ : /\[(.*)\]$/;
        m = reg.exec(line.trim());
        if (m) {
          return m[1];
        } else {
          return false;
        }
      };
      if (typeof text === 'string') {
        text = text.trim();
      }
      if (!text) {
        return callback('');
      }
      start = startDelimiter ? text.indexOf(startDelimiter) + startDelimiter.length : 0;
      end = endDelimiter ? text.indexOf(endDelimiter) : text.length;
      text = text.substr(start, end - start);
      if (!text) {
        return callback('');
      }
      data = text.split('##');
      result = [];
      if (fromFront) {
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          line = data[_i];
          line = line.trim();
          if (!line) {
            continue;
          }
          _r = matchLine(line, true);
          if (!_r) {
            break;
          }
          result.push(_r);
        }
        return callback(result);
      }
      for (_j = 0, _len1 = data.length; _j < _len1; _j++) {
        line = data[_j];
        line = line.trim();
        if (!line) {
          continue;
        }
        _r = matchLine(line);
        if (_r) {
          result.push(_r);
        } else {
          result = [];
        }
      }
      return callback(result);
    };

    refine = function() {
      console.log(queue);
      return parseCallback(queue);
    };

    dragOnceOver = function(startLine, result) {
      startLine += 1;
      if (result && result[0]) {
        queue.push(result);
      }
      if (startLine < contentArrayLength) {
        return drag(startLine);
      }
      return refine();
    };

    HtmlContent.prototype.parse = function(callback) {
      if (contentArrayLength === 0) {
        return callback(false);
      }
      parseCallback = callback;
      /*
      		# drag -> dragOnceOver -> drag -> ... -> refine -> callback
      */

      return drag(0);
    };

    function HtmlContent() {
      this.parse = __bind(this.parse, this);      content = document.body.innerText || document.body.textContent;
      content = content.replace(/[\r\n]/g, '');
      contentArray = content.split('$$$$');
      contentArrayLength = contentArray.length;
    }

    return HtmlContent;

  })();

  $ = null;

  Main = (function() {
    var jQueryPath, load;

    jQueryPath = 'http://lib.sinaapp.com/js/jquery/1.9.1/jquery-1.9.1.min.js';

    load = function(path, callback) {
      var scriptElement;

      scriptElement = document.createElement('script');
      scriptElement.type = 'text/javascript';
      scriptElement.src = path;
      scriptElement.onload = function() {
        return callback();
      };
      return document.body.appendChild(scriptElement);
    };

    Main.prototype.start = function() {
      var build, handle, parse;

      $ = jQuery;
      parse = function() {
        var htmlContent;

        htmlContent = new HtmlContent();
        return htmlContent.parse(function(cardQueue) {
          return handle(cardQueue);
        });
      };
      handle = function(cardQueue) {
        if (typeof cardQueue === 'object' && cardQueue.length > 0) {
          return build(cardQueue.shift(), function() {
            return handle(cardQueue);
          });
        }
      };
      build = function(data, callback) {
        var cardDeck;

        cardDeck = new CardDeck(data);
        return cardDeck.build(callback);
      };
      return $(function() {
        return parse();
      });
    };

    function Main() {
      this.start = __bind(this.start, this);
      var origin$,
        _this = this;

      if (typeof jQuery !== 'undefined') {
        this.start();
      } else {
        origin$ = window.$;
        load(jQueryPath, function() {
          jQuery.noConflict();
          window.$ = origin$;
          return _this.start();
        });
      }
    }

    return Main;

  })();

  if ((_ref = this.myCardUserJS) == null) {
    this.myCardUserJS = new Main();
  }

}).call(this);
