Style =
	container:
		'position': 'absolute'
		'width': '818px'
		'background': '#FFFFFF'
		'padding': '4px'
		'margin': '4px'
		'border': '2px solid #CCCCCC'
		'border-radius': '4px'
		'box-shadow': '0 0 4px #CCCCCC'
	sider:
		'float':  'right'
		'width': '300px'
		'height': '430px'
		'position': 'relative'
	siderNameBox:
		'width': '300px'
		'height': 'auto'
		'padding': '8px 0'
		'margin': 0
		'font-weight': 'bold'
		'text-shadow': '1px 1px 2px #ccc'
		'font-size': '24px'
		'text-align': 'center'
		'background': '#eee'
		'height': '29px'
	siderImageBox:
		'margin': '10px 0 0 10px'
		'height': 'auto'
		'width': 'auto'
		'float': 'left'
	siderInfoBox:
		'width': '135px'
		'height': '180px'
		'padding': '15px 5px 5px 5px'
		'margin': '7px 0 0 10px'
		'float': 'left'
	siderInfoItemName:
		'width': '60px'
		'height': '14px'
		'line-height': '14px'
		'padding-bottom': '5px'
		'margin-bottom': '10px'
		'color': '#ffad6e'
		'font-size': '12px'
		'text-shadow': '1px 1px 2px #eee'
		'border-bottom': '1px dashed #ccc'
		'float': 'left'
	siderInfoItemContent:
		'width': '75px'
		'height': '14px'
		'padding-bottom': '5px'
		'margin-bottom': '10px'
		'font-size': '12px'
		'color': 'thead_bg#999999'
		'text-shadow': '1px 1px 2px #eee'
		'border-bottom': '1px dashed #ccc'
		'white-space': 'nowrap'
		'text-overflow': 'ellipsis'
		'overflow': 'hidden'
		'float': 'left'
	siderDescriptionBox:
		'border-top': '1px solid #CCCCCC'
		'margin': '15px 0 0'
		'padding': '10px'
		'width': '280px'
		'color': '#999999'
		'float': 'left'
	cardImage:
		'float': 'left'
		'margin': '0 3px 8px 3px'
		'overflow': 'visible'
	main:
		'float': 'left'
		'position': 'relative'
	legend:
		'color': '#666666'
		'font-size': '14px'
		'margin-left': '8px'
	fieldset:
		'width': '500px'
		'height': '295px'
		'background': '#F9F9F9'
		'border-radius': '6px'
		'color': '#666666'
		'font-size': '12px'
		'margin': '14px 0 0'
		'padding': '5px'
	operaPanel:
		'height': '24px'
		'margin-top': '6px'
	operaIco:
		'float': 'right'
		'height': '25px'
		'width': '25px'
		'background': 'http://my-card.in/assets/images/decks/download_out.png'
		'mar-right': '6px'
		'overflow': 'hidden'
		'display': 'block'
		'text-align': 'center'
		'font-weight': 'bold'
	operaWhatsThis:
		'font-weight'